#ifndef __MainWindowDesktopWidget__
#define __MainWindowDesktopWidget__

/**
@file
Subclass of DesktopWidget, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing DesktopWidget */

#include "../../graphics/images/widget_bg.h"
class MainWindowDesktopWidget : public DesktopWidget {
protected:
    // Handlers for DesktopWidget events.

    void OnMouseEnter(wxMouseEvent& event) override;
    void OnMouseLeave(wxMouseEvent& event) override;
    void OnMouseLeftDown(wxMouseEvent& event) override;
    void OnMouseLeftUp(wxMouseEvent& event) override;
    void OnMouseMotion(wxMouseEvent& event) override;
    void OnLeftMouseDClick(wxMouseEvent& event) override;
    void OnWidgetPaint(wxPaintEvent& event) override;

public:
    /** Constructor */
    MainWindowDesktopWidget(wxWindow* parent);
    //// end generated class members

private:
    bool dragging = false;
    int x, y;
    wxPoint m_delta;
    wxBitmap m_background;
    void OnThreadMessage(wxThreadEvent& e);
    inline static wxImage LoadImageFromHeader() {
        // A tömb méretének meghatározása
        size_t size = sizeof(widget_bg);

        // Memória alapú adatfolyam létrehozása
        wxMemoryInputStream stream(widget_bg, size);

        // wxImage betöltése az adatfolyamból
        wxImage image;
        if (image.LoadFile(stream, wxBitmapType::wxBITMAP_TYPE_ANY)) {
            if (!image.IsOk()) {
                wxLogError("Failed to load image from header data.");
            }
        } else {
            wxLogError("Image format is not supported or invalid.");
        }

        return image;  // Visszatérünk az elkészített wxImage objektummal
    }
};

#endif  // __MainWindowDesktopWidget__
