#ifndef __MainWindowSettings__
#define __MainWindowSettings__

/**
@file
Subclass of Settings, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include
#include "../libs/cores.h"
#include "utils.hpp"
#include "ver.hpp"

#include <wx/fileconf.h>
#include <wx/secretstore.h>
#include <wx/stdpaths.h>

/** Implementing Settings */
class MainWindowSettings : public Settings
{
	protected:
		// Handlers for Settings events.
		void OnOpenFolder( wxCommandEvent& event );
		void OnTAESDHelpClick( wxCommandEvent& event );
		void OnImgQualityScroll( wxScrollEvent& event );
		void OnImgQualitySpin( wxSpinEvent& event );
		void onShowNotificationCheck( wxCommandEvent& event );
		void OnCivitaiHelpButton( wxCommandEvent& event );
		void OnAddBackend( wxCommandEvent& event );
		void OnRemoveBackend( wxCommandEvent& event );
		void OnBackendListSelectionChanged( wxDataViewEvent& event );
		void onSave( wxCommandEvent& event );
	public:
		/** Constructor */
		MainWindowSettings( wxWindow* parent );
	//// end generated class members
private:
    void InitConfig();
    wxFileConfig* fileConfig;
    sd_gui_utils::config* cfg;
    std::string ini_path;

};

#endif // __MainWindowSettings__
