#ifndef __MainWindowDesktopWidget__
#define __MainWindowDesktopWidget__

/**
@file
Subclass of DesktopWidget, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing DesktopWidget */
class MainWindowDesktopWidget : public DesktopWidget {
protected:
    // Handlers for DesktopWidget events.

    void OnMouseEnter(wxMouseEvent& event) override;
    void OnMouseLeave(wxMouseEvent& event) override;
    void OnMouseLeftDown(wxMouseEvent& event) override;
    void OnMouseLeftUp(wxMouseEvent& event) override;
    void OnMouseMotion(wxMouseEvent& event) override;
    void OnLeftMouseDClick(wxMouseEvent& event) override;
    void OnWidgetPaint(wxPaintEvent& event) override;
    void OnIconize(wxIconizeEvent& event) override;

public:
    /** Constructor */
    MainWindowDesktopWidget(wxWindow* parent);
    void PassParentEventHandler(wxEvtHandler* eventHandler);
    //// end generated class members

private:
    bool dragging = false;
    wxPoint m_delta;
    wxBitmap m_background;
    wxEvtHandler* pEvents = nullptr;
    void OnThreadMessage(wxThreadEvent& e);
};

#endif  // __MainWindowDesktopWidget__
