find_package(md4c QUIET)
if (md4c_FOUND)
    message(STATUS "md4c found: ${MD4C_INCLUDE_DIR} ${MD4C_LIBRARIES}")
endif()
if (NOT md4c_FOUND)

  ExternalProject_Add(md4c
  GIT_REPOSITORY https://github.com/mity/md4c.git
  GIT_TAG "release-0.4.8" # as in ubuntu 24.04
  BUILD_BYPRODUCTS "${CMAKE_CURRENT_BINARY_DIR}/md4c/lib/${CMAKE_STATIC_LIBRARY_PREFIX}md4c${CMAKE_STATIC_LIBRARY_SUFFIX};${CMAKE_CURRENT_BINARY_DIR}/md4c/lib/${CMAKE_STATIC_LIBRARY_PREFIX}md4c-html${CMAKE_STATIC_LIBRARY_SUFFIX}"
  CMAKE_ARGS
    -DCMAKE_INSTALL_PREFIX=${CMAKE_CURRENT_BINARY_DIR}/md4c
    -DCMAKE_BUILD_TYPE=Release
    -DCMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}
    -DCMAKE_CXX_STANDARD_REQUIRED=ON
    -DCMAKE_CXX_EXTENSIONS=OFF
    -DCMAKE_CXX_VISIBILITY_PRESET=hidden
    -DBUILD_MD2HTML_EXECUTABLE=OFF
    -DBUILD_SHARED_LIBS=OFF
  )
  set(MD4C_INCLUDE_DIR ${CMAKE_CURRENT_BINARY_DIR}/md4c/include)
  set(MD4C_LIBRARIES "${CMAKE_CURRENT_BINARY_DIR}/md4c/lib/${CMAKE_STATIC_LIBRARY_PREFIX}md4c-html${CMAKE_STATIC_LIBRARY_SUFFIX};${CMAKE_CURRENT_BINARY_DIR}/md4c/lib/${CMAKE_STATIC_LIBRARY_PREFIX}md4c${CMAKE_STATIC_LIBRARY_SUFFIX}")
  set(md4c_FOUND TRUE)
  message(STATUS "md4c found: ${MD4C_INCLUDE_DIR} ${MD4C_LIBRARIES}")
endif()