#ifndef __MainWindowAboutDialog__
#define __MainWindowAboutDialog__

/**
@file
Subclass of AboutDialog, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing AboutDialog */
class MainWindowAboutDialog : public AboutDialog
{
	protected:
		// Handlers for AboutDialog events.
		void m_aboutOnHtmlLinkClicked( wxHtmlLinkEvent& event );
	public:
		/** Constructor */
		MainWindowAboutDialog( wxWindow* parent );
	//// end generated class members

};

#endif // __MainWindowAboutDialog__
