#ifndef __MainWindowModelinfo__
#define __MainWindowModelinfo__

/**
@file
Subclass of Modelinfo, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include
#include "ModelInfo.h"
#include <wx/persist/toplevel.h>
#include "utils.hpp"

#include <nlohmann/json.hpp>
#include <wx/msgdlg.h>
#include <wx/wxhtml.h>

#include <filesystem>

#include <curlpp/cURLpp.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Options.hpp>
#include <curlpp/Exception.hpp>
#include "embedded_files/app_icon.h"


/** Implementing Modelinfo */
class MainWindowModelinfo : public Modelinfo
{
public:
	/** Constructor */
	MainWindowModelinfo(wxWindow *parent);
	//// end generated class members
	bool SetData(ModelInfo::Manager *ModelManager, std::string model_path, std::string datapath);

private:
	std::string FetchData(std::string hash);
	wxImage FetchImage(std::string url, std::string target);
	void data2Gui();
	void loadImages(nlohmann::json jf);

	std::string url_civitai_base = "https://civitai.com/api/v1/";
	/// @brief Endpoint to retriver model info... need hash to the end
	std::string url_model_info = "model-versions/by-hash/";
	std::string datapath;
	std::string infofile;
	std::vector<wxImage> images;

	sd_gui_utils::ModelFileInfo *ModelInfo;
};

#endif // __MainWindowModelinfo__
