#ifndef __MainWindowImageDialog__
#define __MainWindowImageDialog__

/**
@file
Subclass of ImageDialog, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing ImageDialog */
class MainWindowImageDialog : public ImageDialog
{
	public:
		/** Constructor */
		MainWindowImageDialog( wxWindow* parent );
	//// end generated class members






};

#endif // __MainWindowImageDialog__
