#ifndef __MainWindowImageViewer__
#define __MainWindowImageViewer__

/**
@file
Subclass of ImageViewer, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing ImageViewer */
class MainWindowImageViewer : public ImageViewer
{
	public:
		/** Constructor */
		MainWindowImageViewer( wxWindow* parent );
	//// end generated class members

































};

#endif // __MainWindowImageViewer__
