#ifndef __MainWindowImageViewer__
#define __MainWindowImageViewer__

/**
@file
Subclass of ImageViewer, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include
#include "QueueManager.h"
#include "utils.hpp"
#include <filesystem>

#include "embedded_files/app_icon.h"
#include <wx/persist/toplevel.h>

/** Implementing ImageViewer */
class MainWindowImageViewer : public ImageViewer
{
	public:
		/** Constructor */
		MainWindowImageViewer( wxWindow* parent );
	//// end generated class members

	void SetData(QM::QueueItem item);

private:
	QM::QueueItem myItem;
	void OnThumbnailClick(wxMouseEvent &event);


};

#endif // __MainWindowImageViewer__
