#ifndef __MainWindowImage__
#define __MainWindowImage__

/**
@file
Subclass of Image, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing Image */
class MainWindowImage : public Image
{
	public:
		/** Constructor */
		MainWindowImage( wxWindow* parent );
	//// end generated class members



};

#endif // __MainWindowImage__
