#ifndef __MainWindowModelinfo__
#define __MainWindowModelinfo__

/**
@file
Subclass of Modelinfo, which is generated by wxFormBuilder.
*/

#include "MainWindow.h"

//// end generated include

/** Implementing Modelinfo */
class MainWindowModelinfo : public Modelinfo
{
	public:
		/** Constructor */
		MainWindowModelinfo( wxWindow* parent );
	//// end generated class members

};

#endif // __MainWindowModelinfo__
