name: Multi build and package - windows

on:
    workflow_dispatch:

jobs:
  build-windows-cpu:
    name: Build on Windows with CPU features
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            $conan_version=conan --version
            echo "conan_version=$conan_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8

      - name: Set up Conan
        run: |
          mkdir build
          cd build
          conan profile detect
          conan install .. -s compiler.cppstd=17 --build=never

      - name: Configure CMake for CPU
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSD_AVX=ON -DSD_AVX2=ON -DSD_AVX512=ON --preset conan-default

      - name: Build for CPU
        run: |
          cd build
          cmake --build . --config Release --target stable_diffusion_cpp_avx
          cmake --build . --config Release --target stable_diffusion_cpp_avx2
          cmake --build . --config Release --target stable_diffusion_cpp_avx512

      - name: Upload CPU build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-cpu
          path: build/
          compression-level: 0
          overwrite: true

  build-windows-cuda:
    name: Build on Windows with CUDA
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install CUDA Toolkit
        uses: Jimver/cuda-toolkit@v0.2.11
        with:
          cuda: "12.2.0"

      - name: Install Conan
        id: conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            $conan_version=conan --version
            echo "conan_version=$conan_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8          

      - name: Set up Conan
        run: |
          mkdir build
          cd build
          conan profile detect
          conan install .. -s compiler.cppstd=17 --build=never

      - name: Configure CMake for CUDA
        run: |
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -DSD_CUBLAS=ON --preset conan-default

      - name: Build CUDA
        run: |
          cd build
          cmake --build . --config Release --target stable_diffusion_cpp_cuda

      - name: Upload CUDA build directory
        uses: actions/upload-artifact@v4
        with:
          name: build-cuda
          path: build/
          compression-level: 0
          overwrite: true

  build-windows-hipblas:
    name: Build on Windows with HIPBLAS
    runs-on: windows-2019
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Conan
        id: conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            $conan_version=conan --version
            echo "conan_version=$conan_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
                   
      - name: Install rocm-toolkit
        id: rocm-toolkit
        uses: Cyberhan123/rocm-toolkit@v0.1.0
        with:
          rocm: "5.5.0"
      
      - name: Install Ninja
        id: install-ninja
        uses: urkle/action-get-ninja@v1
        with:
          version: 1.11.1

      - name: Set up Conan
        run: |
            mkdir build
            cd build
            conan profile detect
            conan install .. -s compiler.cppstd=17 --build=never
  
      - name: Configure CMake for HIPBLAS
        run: |
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DSD_HIPBLAS=ON --preset conan-default
  
      - name: Build HIPBLAS
        run: |
            cd build
            cmake --build . --config Release --target stable_diffusion_cpp_hipblas
  
      - name: Upload HIPBLAS build directory
        uses: actions/upload-artifact@v4
        with:
           name: build-hipblas
           path: build/
           compression-level: 0
           overwrite: true

  build-windows-vulkan:
    name: Build on Windows with VULKAN
    runs-on: windows-2019
    env:
        VULKAN_VERSION: 1.3.261.1    
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Install Vulkan SDK
        id: get_vulkan
        run: |
          curl.exe -o $env:RUNNER_TEMP/VulkanSDK-Installer.exe -L "https://sdk.lunarg.com/sdk/download/${env:VULKAN_VERSION}/windows/VulkanSDK-${env:VULKAN_VERSION}-Installer.exe"
          & "$env:RUNNER_TEMP\VulkanSDK-Installer.exe" --accept-licenses --default-answer --confirm-command install
          Add-Content $env:GITHUB_ENV "VULKAN_SDK=C:\VulkanSDK\${env:VULKAN_VERSION}"
          Add-Content $env:GITHUB_PATH "C:\VulkanSDK\${env:VULKAN_VERSION}\bin"

      - name: Install Conan
        id: conan
        run: |
            python -m pip install --upgrade pip
            pip install conan
            $conan_version=conan --version
            echo "conan_version=$conan_version" | Out-File -FilePath $env:GITHUB_ENV -Encoding utf8
      
      - name: Install Ninja
        id: install-ninja
        uses: urkle/action-get-ninja@v1
        with:
          version: 1.11.1

      - name: Set up Conan
        run: |
            mkdir build
            cd build
            conan profile detect
            conan install .. -s compiler.cppstd=17 --build=never
  
      - name: Configure CMake for HIPBLAS
        run: |
            cd build
            cmake .. -DCMAKE_BUILD_TYPE=Release -DSD_HIPBLAS=ON --preset conan-default
  
      - name: Build HIPBLAS
        run: |
            cd build
            cmake --build . --config Release --target stable_diffusion_cpp_hipblas
  
      - name: Upload HIPBLAS build directory
        uses: actions/upload-artifact@v4
        with:
           name: build-hipblas
           path: build/
           compression-level: 0
           overwrite: true

  package-installer:
    name: Create Windows Installer
    runs-on: windows-2019
    needs: [build-windows-cpu, build-windows-cuda, build-windows-hipblas, build-windows-vulkan]
    steps:
      - name: Check out code
        uses: actions/checkout@v3        
      
      - name: Download CPU build directory
        uses: actions/download-artifact@v4
        with:
          name: build-cpu
          path: build-cpu/

      - name: Download CUDA build directory
        uses: actions/download-artifact@v4
        with:
          name: build-cuda
          path: build-cuda/

      - name: Download HIPBLAS build directory
        uses: actions/download-artifact@v4
        with:
          name: build-hipblas
          path: build-hipblas/          

      - name: Merge build outputs
        run: |
          mkdir build
          copy build-cpu/* build/ /y
          copy build-cuda/* build/ /y
          copy build-hipblas/* build/ /y          

      - name: Generate NSIS installer
        run: |
          cd build
          cmake --build . --config Release --target package

      - name: Release NSIS Installer
        uses: softprops/action-gh-release@v2
        with:
          body: ""
          draft: true
          prerelease: true

          files: |
            build/*.exe
            build/*.sha256
