#!/bin/bash
# postinst script for stablediffusiongui-server
set -e

chmod -f +x /usr/bin/stablediffusiongui_server
chmod -f +x /usr/bin/stablediffusiongui_diffuser

if [ -d /run/systemd/system ]; then

    echo "Adding service file"
    cp -p /usr/share/stablediffusiongui/stablediffusiongui_server.service /lib/systemd/system/stablediffusiongui_server.service
    echo "Reloading systemd daemon..."
    systemctl --system daemon-reload >/dev/null || true
    echo "Enabling stablediffusiongui_server.service..."
    systemctl enable stablediffusiongui_server.service ||

    echo "Please see the config file before starting the service!"

fi


CONF_FILE="/etc/stablediffusiongui_server/server.json"

    if [ ! -f "$CONF_FILE" ]; then
        mkdir /etc/stablediffusiongui_server
        cp /usr/share/stablediffusiongui/server.json "$CONF_FILE"
        mkdir -p /var/lib/stable-diffusion-server/models/{checkpoints,controlnet,embedding,esrgan,loras,taesd,vae}
    fi

exit 0