#ifndef _NETWORK_REMOTE_QUEUE_JOB_ITEM_H_
#define _NETWORK_REMOTE_QUEUE_JOB_ITEM_H_

namespace sd_gui_utils {

    inline namespace networks {

        enum class ImageType : unsigned int {
            /// @brief The image is generated by diffusion
            GENERATED = 1 << 0,
            /// @brief The image is added by user into the controlnet
            CONTROLNET = 1 << 1,
            /// @brief This is an itial image (eg. img2img original image, or upscaler original image)
            INITIAL = 1 << 2,
            /// @brief The image is a mask image on img2img
            MASK = 1 << 3,
            /// @brief The image is a tmp image, deletable
            TMP = 1 << 4,
            /// @brief The original image, if in img2img the initial image is resized to outpaint
            ORIGINAL      = 1 << 5,
            MASK_OUTPAINT = 1 << 6,
            MASK_INPAINT  = 1 << 7,
            MASK_USED     = 1 << 8,
            UNKNOWN
        };
        inline ImageType operator|(ImageType lhs, ImageType rhs) {
            return static_cast<ImageType>(static_cast<unsigned int>(lhs) | static_cast<unsigned int>(rhs));
        }

        inline ImageType& operator|=(ImageType& lhs, ImageType rhs) {
            lhs = lhs | rhs;
            return lhs;
        }
        inline bool hasImageType(ImageType combinedType, ImageType singleType) {
            return (static_cast<unsigned int>(combinedType) & static_cast<unsigned int>(singleType)) != 0;
        }

        struct ItemImage {
            sd_gui_utils::ImageType type = sd_gui_utils::ImageType::GENERATED;
            std::vector<unsigned char> rawData;
        };

        struct RemoteQueueItem {
            uint64_t id = 0, created_at = 0, updated_at = 0, finished_at = 0, started_at = 0;
            SDParams params      = SDParams();
            QueueStatus status   = QueueStatus::PENDING;
            QueueEvents event    = QueueEvents::ITEM_ADDED;
            QueueItemStats stats = QueueItemStats();
            int step = 0, steps = 0;
            size_t hash_fullsize = 0, hash_progress_size = 0;
            float time                           = 0;
            std::string model                    = "";
            SDMode mode                          = SDMode::TXT2IMG;
            std::string status_message           = "";
            uint32_t upscale_factor              = 4;
            std::string sha256                   = "";
            std::string app_version              = SD_GUI_VERSION;
            std::string git_version              = GIT_HASH;
            std::string original_prompt          = "";
            std::string original_negative_prompt = "";
            bool keep_checkpoint_in_memory       = false;
            bool keep_upscaler_in_memory         = false;
            bool need_sha256                     = false;
            std::string generated_sha256         = "";
            int update_index                     = -1;
            std::string server                   = "";
            std::vector<ItemImage> image_data    = {};
        };
        NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE_WITH_DEFAULT(RemoteQueueItem,
                                                        id,
                                                        created_at,
                                                        updated_at,
                                                        finished_at,
                                                        started_at,
                                                        params,
                                                        status,
                                                        event,
                                                        stats,
                                                        step,
                                                        steps,
                                                        hash_fullsize,
                                                        hash_progress_size,
                                                        time,
                                                        model,
                                                        mode,
                                                        status_message,
                                                        upscale_factor,
                                                        sha256,
                                                        app_version,
                                                        git_version,
                                                        original_prompt,
                                                        original_negative_prompt,
                                                        keep_checkpoint_in_memory,
                                                        keep_upscaler_in_memory,
                                                        need_sha256,
                                                        generated_sha256,
                                                        update_index,
                                                        server)
    }  // namespace networks
}  // namespace sd_gui_utils

#endif  // _NETWORK_REMOTE_QUEUE_JOB_ITEM_H_